"""Firmware templates for Hargassner pellet boilers.

This module contains XML templates (DAQPRJ format) that define the parameter
structure for different firmware versions of Hargassner boilers.
"""

from __future__ import annotations

from typing import Final

# Firmware Templates
#
# XML templates in DAQPRJ format from Hargassner DAQ files.
# These define the structure and order of telnet message parameters
#
# To add support for a new firmware version:
# 1. Use tools/daq_parser.py to extract the DAQPRJ template from a DAQ file
# 2. Add it here with a descriptive version key (e.g., "NANO_V15X")
# 3. Update FIRMWARE_VERSIONS in const.py

FIRMWARE_TEMPLATES: Final[dict[str, str]] = {
    "V14_1HAR_q1": """<DAQPRJ><ANALOG><CHANNEL id='0' name='ZK' dop='0'/><CHANNEL id='1' name='O2' unit='%'/><CHANNEL id='2' name='O2soll' unit='%'/><CHANNEL id='3' name='TK' unit='°C'/><CHANNEL id='4' name='TKsoll' unit='°C'/><CHANNEL id='5' name='TRL' unit='°C'/><CHANNEL id='6' name='TRLsoll' unit='°C' dop='0'/><CHANNEL id='7' name='Spreizung' unit='°C'/><CHANNEL id='8' name='TRG' unit='°C'/><CHANNEL id='9' name='SZist' unit='%' dop='0'/><CHANNEL id='10' name='SZsoll' unit='%'/><CHANNEL id='11' name='TPo' unit='°C'/><CHANNEL id='12' name='TPm' unit='°C'/><CHANNEL id='13' name='TPu' unit='°C'/><CHANNEL id='14' name='Puff Füllgrad' unit='%' dop='0'/><CHANNEL id='15' name='Puffer_soll oben' unit='°C' dop='0'/><CHANNEL id='16' name='Puffer_soll unten' unit='°C' dop='0'/><CHANNEL id='17' name='PuffZustand' dop='0'/><CHANNEL id='18' name='Max Anf Kessel' dop='0'/><CHANNEL id='19' name='TFW' unit='°C' dop='0'/><CHANNEL id='20' name='Leistung' unit='%' dop='0'/><CHANNEL id='21' name='ESsoll' unit='%'/><CHANNEL id='22' name='min.Leist.TRG' unit='%'/><CHANNEL id='23' name='max.Leist.TRG' unit='%'/><CHANNEL id='24' name='max.Leist.Fuell' unit='%'/><CHANNEL id='25' name='max.Leist.TPO' unit='%'/><CHANNEL id='26' name='ESRegler' unit='%' dop='0'/><CHANNEL id='27' name='Regler K'/><CHANNEL id='28' name='KeBrstScale' unit='%' dop='0'/><CHANNEL id='29' name='Programm' dop='0'/><CHANNEL id='30' name='Störungs Nr' dop='0'/><CHANNEL id='31' name='Max Anf ZenPuf' unit='°C' dop='0'/><CHANNEL id='32' name='I Es' unit='mA' dop='0'/><CHANNEL id='33' name='I Ra' unit='mA' dop='0'/><CHANNEL id='34' name='I Aa' unit='mA' dop='0'/><CHANNEL id='35' name='I Sr' unit='mA' dop='0'/><CHANNEL id='36' name='I Rein' unit='mA' dop='0'/><CHANNEL id='37' name='BLDC_ES ist' unit='rpm' dop='0'/><CHANNEL id='38' name='BLDC_ES soll' unit='rpm' dop='0'/><CHANNEL id='39' name='LZ ES seit Füll.' unit='Min' dop='0'/><CHANNEL id='40' name='LZ ES seit Ent.' unit='Min' dop='0'/><CHANNEL id='41' name='Anzahl Entasch.' dop='0'/><CHANNEL id='42' name='Anzahl SR Beweg.' dop='0'/><CHANNEL id='43' name='Lagerstand' unit='kg' dop='0'/><CHANNEL id='44' name='Verbrauchszähler' unit='kg' dop='0'/><CHANNEL id='45' name='Heiz P Lambda' unit='W' dop='2'/><CHANNEL id='46' name='Heiz U Lambda' unit='V' dop='2'/><CHANNEL id='47' name='Heiz I Lambda' unit='mA' dop='0'/><CHANNEL id='48' name='U_Lambda' unit='mV'/><CHANNEL id='49' name='U Netzteil' unit='mV' dop='0'/><CHANNEL id='50' name='T Spülung' unit='°C'/><CHANNEL id='51' name='BRT' unit='°C'/><CHANNEL id='52' name='Tplat' unit='°C' dop='0'/><CHANNEL id='53' name='TVG' unit='°C'/><CHANNEL id='54' name='TVG2' unit='°C'/><CHANNEL id='55' name='AIN17' unit='V'/><CHANNEL id='56' name='Taus' unit='°C'/><CHANNEL id='57' name='TA Gem.' unit='°C'/><CHANNEL id='58' name='Effizienz' unit='%'/><CHANNEL id='59' name='ExtHK Solltmp.' unit='°C' dop='0'/><CHANNEL id='60' name='TVL_A' unit='°C'/><CHANNEL id='61' name='TVLs_A' unit='°C' dop='0'/><CHANNEL id='62' name='TRA_A' unit='°C'/><CHANNEL id='63' name='TRs_A' unit='°C'/><CHANNEL id='64' name='HKZustand_A' dop='0'/><CHANNEL id='65' name='FRA Zustand' dop='0'/><CHANNEL id='66' name='HKPA Status' dop='0'/><CHANNEL id='67' name='TVL_1' unit='°C'/><CHANNEL id='68' name='TVLs_1' unit='°C' dop='0'/><CHANNEL id='69' name='TRA_1' unit='°C'/><CHANNEL id='70' name='TRs_1' unit='°C'/><CHANNEL id='71' name='HKZustand_1' dop='0'/><CHANNEL id='72' name='FR1 Zustand' dop='0'/><CHANNEL id='73' name='HKP1 Status' dop='0'/><CHANNEL id='74' name='TVL_2' unit='°C'/><CHANNEL id='75' name='TVLs_2' unit='°C' dop='0'/><CHANNEL id='76' name='TRA_2' unit='°C'/><CHANNEL id='77' name='TRs_2' unit='°C'/><CHANNEL id='78' name='HKZustand_2' dop='0'/><CHANNEL id='79' name='FR2 Zustand' dop='0'/><CHANNEL id='80' name='HKP2 Status' dop='0'/><CHANNEL id='81' name='TVL_B' unit='°C'/><CHANNEL id='82' name='TVLs_B' unit='°C' dop='0'/><CHANNEL id='83' name='TRA_B' unit='°C'/><CHANNEL id='84' name='TRs_B' unit='°C'/><CHANNEL id='85' name='HKZustand_B' dop='0'/><CHANNEL id='86' name='FRB Zustand' dop='0'/><CHANNEL id='87' name='HKPB Status' dop='0'/><CHANNEL id='88' name='TBA' unit='°C'/><CHANNEL id='89' name='TBs_A' unit='°C' dop='0'/><CHANNEL id='90' name='TB1' unit='°C'/><CHANNEL id='91' name='TBs_1' unit='°C' dop='0'/><CHANNEL id='92' name='TBB' unit='°C'/><CHANNEL id='93' name='TBs_B' unit='°C' dop='0'/><CHANNEL id='94' name='HKR Anf' unit='°C'/><CHANNEL id='95' name='Anf. HKR0' unit='°C' dop='0'/><CHANNEL id='96' name='Anf. HKR1' unit='°C' dop='0'/><CHANNEL id='97' name='Anf. HKR2' unit='°C' dop='0'/><CHANNEL id='98' name='Anf. HKR3' unit='°C' dop='0'/><CHANNEL id='99' name='Anf. HKR4' unit='°C' dop='0'/><CHANNEL id='100' name='Anf. HKR5' unit='°C' dop='0'/><CHANNEL id='101' name='Anf. HKR6' unit='°C' dop='0'/><CHANNEL id='102' name='Anf. HKR7' unit='°C' dop='0'/><CHANNEL id='103' name='Anf. HKR8' unit='°C' dop='0'/><CHANNEL id='104' name='Anf. HKR9' unit='°C' dop='0'/><CHANNEL id='105' name='Anf. HKR10' unit='°C' dop='0'/><CHANNEL id='106' name='Anf. HKR11' unit='°C' dop='0'/><CHANNEL id='107' name='Anf. HKR12' unit='°C' dop='0'/><CHANNEL id='108' name='Anf. HKR13' unit='°C' dop='0'/><CHANNEL id='109' name='Anf. HKR14' unit='°C' dop='0'/><CHANNEL id='110' name='Anf. HKR15' unit='°C' dop='0'/><CHANNEL id='111' name='Wasserdruck' unit='bar' dop='2'/></ANALOG><DIGITAL><CHANNEL id='0' bit='0' name='Störung'/><CHANNEL id='0' bit='1' name='Stb'/><CHANNEL id='0' bit='2' name='Fuellstand'/><CHANNEL id='0' bit='3' name='RLP/PuffP'/><CHANNEL id='0' bit='4' name='RLm_auf'/><CHANNEL id='0' bit='5' name='RLm_zu'/><CHANNEL id='0' bit='10' name='WS freig.'/><CHANNEL id='0' bit='11' name='Akt. Code'/><CHANNEL id='0' bit='14' name='FW Freig.'/><CHANNEL id='0' bit='15' name='gFlP'/><CHANNEL id='0' bit='16' name='gFlM auf'/><CHANNEL id='0' bit='17' name='gFlM zu'/><CHANNEL id='0' bit='18' name='gFl2P'/><CHANNEL id='0' bit='19' name='gFl2M auf'/><CHANNEL id='0' bit='20' name='gFl2M zu'/><CHANNEL id='1' bit='0' name='L Heiz.'/><CHANNEL id='1' bit='1' name='Z Heiz.'/><CHANNEL id='1' bit='2' name='Z Geb.'/><CHANNEL id='1' bit='3' name='AA Run'/><CHANNEL id='1' bit='4' name='AA Dir'/><CHANNEL id='1' bit='5' name='ES Run'/><CHANNEL id='1' bit='6' name='ES Dir'/><CHANNEL id='1' bit='7' name='AS Saug'/><CHANNEL id='1' bit='8' name='AS RA Run'/><CHANNEL id='1' bit='9' name='AS RA Dir'/><CHANNEL id='1' bit='10' name='Rein En'/><CHANNEL id='1' bit='11' name='Rein Run'/><CHANNEL id='1' bit='12' name='Es Rein Endl'/><CHANNEL id='1' bit='13' name='sAS Anf Füll'/><CHANNEL id='2' bit='0' name='HKPA'/><CHANNEL id='2' bit='1' name='MAA'/><CHANNEL id='2' bit='2' name='MAZ'/><CHANNEL id='2' bit='3' name='HKP1'/><CHANNEL id='2' bit='4' name='M1A'/><CHANNEL id='2' bit='5' name='M1Z'/><CHANNEL id='2' bit='6' name='HKP2'/><CHANNEL id='2' bit='7' name='M2A'/><CHANNEL id='2' bit='8' name='M2Z'/><CHANNEL id='2' bit='9' name='HKP3'/><CHANNEL id='2' bit='10' name='M3A'/><CHANNEL id='2' bit='11' name='M3Z'/><CHANNEL id='2' bit='12' name='HKP4'/><CHANNEL id='2' bit='13' name='M4A'/><CHANNEL id='2' bit='14' name='M4Z'/><CHANNEL id='2' bit='15' name='HKP5'/><CHANNEL id='2' bit='16' name='M5A'/><CHANNEL id='2' bit='17' name='M5Z'/><CHANNEL id='2' bit='18' name='HKP6'/><CHANNEL id='2' bit='19' name='M6A'/><CHANNEL id='2' bit='20' name='M6Z'/><CHANNEL id='2' bit='21' name='HKPB'/><CHANNEL id='2' bit='22' name='MBA'/><CHANNEL id='2' bit='23' name='MBZ'/><CHANNEL id='2' bit='24' name='HK-P Poolp'/><CHANNEL id='2' bit='25' name='HK-P Primp'/><CHANNEL id='2' bit='26' name='HK-P MA'/><CHANNEL id='2' bit='27' name='HK-P MZ'/><CHANNEL id='3' bit='0' name='BPA'/><CHANNEL id='3' bit='1' name='BP1'/><CHANNEL id='3' bit='2' name='BP2'/><CHANNEL id='3' bit='3' name='BP3'/><CHANNEL id='3' bit='4' name='BPB'/><CHANNEL id='3' bit='5' name='BZPA'/><CHANNEL id='3' bit='6' name='BZP1'/><CHANNEL id='3' bit='7' name='BZP2'/><CHANNEL id='3' bit='8' name='BZP3'/><CHANNEL id='3' bit='9' name='BZPB'/><CHANNEL id='4' bit='0' name='Aschebox'/><CHANNEL id='4' bit='1' name='Netztrafo'/><CHANNEL id='4' bit='2' name='Netzrelais'/><CHANNEL id='4' bit='4' name='Lagerraum'/><CHANNEL id='4' bit='6' name='FLP'/><CHANNEL id='4' bit='8' name='ATW'/><CHANNEL id='4' bit='9' name='Entasch gesp.'/><CHANNEL id='4' bit='13' name='HKV'/><CHANNEL id='4' bit='14' name='Spülung Aktiv'/><CHANNEL id='4' bit='15' name='ExtHK vorh'/><CHANNEL id='4' bit='16' name='ExtHK_2 vorh'/><CHANNEL id='4' bit='17' name='ExtHK_3 vorh'/><CHANNEL id='6' bit='0' name='ExtHK Anf'/><CHANNEL id='6' bit='2' name='ExtHK_2 Anf'/><CHANNEL id='6' bit='3' name='ExtHK_3 Anf'/><CHANNEL id='6' bit='4' name='ExtHK Pumpe'/><CHANNEL id='6' bit='6' name='ExtHK_2 Pumpe'/><CHANNEL id='6' bit='7' name='ExtHK_3 Pumpe'/><CHANNEL id='6' bit='8' name='KASK1 MinLeist'/><CHANNEL id='6' bit='9' name='KASK2 MinLeist'/><CHANNEL id='6' bit='10' name='KASK3 MinLeist'/><CHANNEL id='6' bit='11' name='KASK4 MinLeist'/><CHANNEL id='6' bit='12' name='KASK1 MaxLeist'/><CHANNEL id='6' bit='13' name='KASK2 MaxLeist'/><CHANNEL id='6' bit='14' name='KASK3 MaxLeist'/><CHANNEL id='6' bit='15' name='KASK4 MaxLeist'/><CHANNEL id='6' bit='16' name='KASK1 Run'/><CHANNEL id='6' bit='17' name='KASK2 Run'/><CHANNEL id='6' bit='18' name='KASK3 Run'/><CHANNEL id='6' bit='19' name='KASK4 Run'/><CHANNEL id='6' bit='20' name='KASK1 OK'/><CHANNEL id='6' bit='21' name='KASK2 OK'/><CHANNEL id='6' bit='22' name='KASK3 OK'/><CHANNEL id='6' bit='23' name='KASK4 OK'/><CHANNEL id='6' bit='24' name='Kask KWK Out'/><CHANNEL id='6' bit='25' name='Kask FW Out'/><CHANNEL id='6' bit='26' name='KASK KWK OK'/><CHANNEL id='6' bit='27' name='KASK FW OK'/><CHANNEL id='7' bit='0' name='DReg P2'/><CHANNEL id='7' bit='1' name='DReg P3'/><CHANNEL id='7' bit='2' name='DReg Mi auf'/><CHANNEL id='7' bit='3' name='DReg Mi zu'/><CHANNEL id='7' bit='5' name='DReg2 P2'/><CHANNEL id='7' bit='6' name='DReg2 Mi auf'/><CHANNEL id='7' bit='7' name='DReg2 Mi zu'/><CHANNEL id='7' bit='9' name='DReg3 P2'/><CHANNEL id='7' bit='10' name='DReg3 P3'/><CHANNEL id='7' bit='11' name='DReg3 Mi auf'/><CHANNEL id='7' bit='12' name='DReg3 Mi zu'/></DIGITAL></DAQPRJ>""",
}

# Complete parameter descriptions for all parameters in DAQPRJ templates
# Format: {"parameter_name": {"en": "English description", "de": "Deutsche Beschreibung"}}
PARAMETER_DESCRIPTIONS: Final[dict[str, dict[str, str]]] = {
    # Boiler core parameters (analog 0-10)
    "ZK": {"en": "Boiler state", "de": "Kesselzustand"},
    "O2": {"en": "O2 level", "de": "O2-Gehalt"},
    "Abgas": {"en": "Smoke gas temperature", "de": "Rauchgastemperatur"},
    "Kessel": {"en": "Boiler temperature", "de": "Kesseltemperatur"},
    "Kesselsoll": {"en": "Boiler temperature target", "de": "Kesseltemperatur Soll"},
    "Puff_o": {"en": "Buffer temperature top", "de": "Puffertemperatur oben"},
    "Puff_u": {"en": "Buffer temperature bottom", "de": "Puffertemperatur unten"},
    "Lambda": {"en": "Lambda value", "de": "Lambda-Wert"},
    "Leist": {"en": "Output power", "de": "Leistung"},
    "Außen": {"en": "Outside temperature", "de": "Außentemperatur"},
    "Saug": {"en": "Draft pressure", "de": "Saugzug"},
    # Buffer temperatures (analog 11-22)
    "Puffer_s_oben": {"en": "Buffer setpoint top", "de": "Puffer Sollwert oben"},
    "Puffer_s_unten": {"en": "Buffer setpoint bottom", "de": "Puffer Sollwert unten"},
    "Boiler": {"en": "Hot water boiler temperature", "de": "Warmwasser Boilertemperatur"},
    "Boilersoll": {"en": "Hot water boiler target", "de": "Warmwasser Boiler Soll"},
    "Solar": {"en": "Solar temperature", "de": "Solartemperatur"},
    "Kollektor": {"en": "Solar collector temperature", "de": "Kollektortemperatur"},
    "Puff_aS_oben": {"en": "Buffer alternative sensor top", "de": "Puffer alternativer Sensor oben"},
    "Puff_aS_unten": {"en": "Buffer alternative sensor bottom", "de": "Puffer alternativer Sensor unten"},
    "Puff_Füllgrad": {"en": "Buffer fill level", "de": "Pufferfüllgrad"},
    "Puffer_soll_oben": {"en": "Buffer target top", "de": "Puffer Zielwert oben"},
    "Puffer_soll_unten": {"en": "Buffer target bottom", "de": "Puffer Zielwert unten"},
    "Max_Anf_Kessel": {"en": "Maximum boiler request", "de": "Maximale Kesselanforderung"},
    # Heating circuits HK1-HK4 (analog 23-43)
    "HK1_VL": {"en": "Heating circuit 1 flow temperature", "de": "Heizkreis 1 Vorlauftemperatur"},
    "HK1_VLsoll": {"en": "Heating circuit 1 flow target", "de": "Heizkreis 1 Vorlauf Soll"},
    "HK1_RT": {"en": "Heating circuit 1 room temperature", "de": "Heizkreis 1 Raumtemperatur"},
    "HK1_RTsoll": {"en": "Heating circuit 1 room target", "de": "Heizkreis 1 Raum Soll"},
    "HK2_VL": {"en": "Heating circuit 2 flow temperature", "de": "Heizkreis 2 Vorlauftemperatur"},
    "HK2_VLsoll": {"en": "Heating circuit 2 flow target", "de": "Heizkreis 2 Vorlauf Soll"},
    "HK2_RT": {"en": "Heating circuit 2 room temperature", "de": "Heizkreis 2 Raumtemperatur"},
    "HK2_RTsoll": {"en": "Heating circuit 2 room target", "de": "Heizkreis 2 Raum Soll"},
    "HK3_VL": {"en": "Heating circuit 3 flow temperature", "de": "Heizkreis 3 Vorlauftemperatur"},
    "HK3_VLsoll": {"en": "Heating circuit 3 flow target", "de": "Heizkreis 3 Vorlauf Soll"},
    "HK3_RT": {"en": "Heating circuit 3 room temperature", "de": "Heizkreis 3 Raumtemperatur"},
    "HK3_RTsoll": {"en": "Heating circuit 3 room target", "de": "Heizkreis 3 Raum Soll"},
    "Raumsoll_Set": {"en": "Room temperature setpoint", "de": "Raum Solltemperatur Einstellung"},
    "HK4_VL": {"en": "Heating circuit 4 flow temperature", "de": "Heizkreis 4 Vorlauftemperatur"},
    "HK4_VLsoll": {"en": "Heating circuit 4 flow target", "de": "Heizkreis 4 Vorlauf Soll"},
    "HK4_RT": {"en": "Heating circuit 4 room temperature", "de": "Heizkreis 4 Raumtemperatur"},
    "HK4_RTsoll": {"en": "Heating circuit 4 room target", "de": "Heizkreis 4 Raum Soll"},
    "HK1_Ventilpos": {"en": "Heating circuit 1 valve position", "de": "Heizkreis 1 Ventilposition"},
    "HK2_Ventilpos": {"en": "Heating circuit 2 valve position", "de": "Heizkreis 2 Ventilposition"},
    "HK3_Ventilpos": {"en": "Heating circuit 3 valve position", "de": "Heizkreis 3 Ventilposition"},
    "HK4_Ventilpos": {"en": "Heating circuit 4 valve position", "de": "Heizkreis 4 Ventilposition"},
    # Pellet storage (analog 44-46)
    "Pellets_Vorrat_kg": {"en": "Pellet stock", "de": "Pelletsvorrat"},
    "Pellets_Verb_kg": {"en": "Pellet consumption", "de": "Pelletsverbrauch"},
    "Austrag": {"en": "Discharge rate", "de": "Austragungsrate"},
    # Analog inputs (analog 47-53)
    "AN11": {"en": "Analog input 11", "de": "Analogeingang 11"},
    "AN12": {"en": "Analog input 12", "de": "Analogeingang 12"},
    "AN13": {"en": "Analog input 13", "de": "Analogeingang 13"},
    "AN14": {"en": "Analog input 14", "de": "Analogeingang 14"},
    "AN15": {"en": "Analog input 15", "de": "Analogeingang 15"},
    "AN16": {"en": "Analog input 16", "de": "Analogeingang 16"},
    "Netzteil": {"en": "Power supply voltage", "de": "Netzteilspannung"},
    # Heating circuit differences (analog 54-57)
    "Diff_HK1": {"en": "Heating circuit 1 differential", "de": "Heizkreis 1 Differenz"},
    "Diff_HK2": {"en": "Heating circuit 2 differential", "de": "Heizkreis 2 Differenz"},
    "Diff_HK3": {"en": "Heating circuit 3 differential", "de": "Heizkreis 3 Differenz"},
    "Diff_HK4": {"en": "Heating circuit 4 differential", "de": "Heizkreis 4 Differenz"},
    # Heating circuit modes (analog 58-69)
    "HK1_PARTY": {"en": "Heating circuit 1 party mode", "de": "Heizkreis 1 Party-Modus"},
    "HK1_FERIEN": {"en": "Heating circuit 1 vacation mode", "de": "Heizkreis 1 Ferienmodus"},
    "HK1_SPARBETRIEB": {"en": "Heating circuit 1 economy mode", "de": "Heizkreis 1 Sparbetrieb"},
    "HK2_PARTY": {"en": "Heating circuit 2 party mode", "de": "Heizkreis 2 Party-Modus"},
    "HK2_FERIEN": {"en": "Heating circuit 2 vacation mode", "de": "Heizkreis 2 Ferienmodus"},
    "HK2_SPARBETRIEB": {"en": "Heating circuit 2 economy mode", "de": "Heizkreis 2 Sparbetrieb"},
    "HK3_PARTY": {"en": "Heating circuit 3 party mode", "de": "Heizkreis 3 Party-Modus"},
    "HK3_FERIEN": {"en": "Heating circuit 3 vacation mode", "de": "Heizkreis 3 Ferienmodus"},
    "HK3_SPARBETRIEB": {"en": "Heating circuit 3 economy mode", "de": "Heizkreis 3 Sparbetrieb"},
    "HK4_PARTY": {"en": "Heating circuit 4 party mode", "de": "Heizkreis 4 Party-Modus"},
    "HK4_FERIEN": {"en": "Heating circuit 4 vacation mode", "de": "Heizkreis 4 Ferienmodus"},
    "HK4_SPARBETRIEB": {"en": "Heating circuit 4 economy mode", "de": "Heizkreis 4 Sparbetrieb"},
    # System status (analog 70-74)
    "BETRIEBSST": {"en": "Operating state", "de": "Betriebszustand"},
    "FEHLERCODE": {"en": "Error code", "de": "Fehlercode"},
    "STATUS_A": {"en": "Status A", "de": "Status A"},
    "STATUS_D": {"en": "Status D", "de": "Status D"},
    "Asche_KG": {"en": "Ash weight", "de": "Aschegewicht"},
    # Party time counters (analog 75-78)
    "PARTYTIME_HK1": {"en": "Heating circuit 1 party time remaining", "de": "Heizkreis 1 Partyzeit verbleibend"},
    "PARTYTIME_HK2": {"en": "Heating circuit 2 party time remaining", "de": "Heizkreis 2 Partyzeit verbleibend"},
    "PARTYTIME_HK3": {"en": "Heating circuit 3 party time remaining", "de": "Heizkreis 3 Partyzeit verbleibend"},
    "PARTYTIME_HK4": {"en": "Heating circuit 4 party time remaining", "de": "Heizkreis 4 Partyzeit verbleibend"},
    # System time (analog 79-84)
    "SYSTEMZEIT_MIN": {"en": "System time minutes", "de": "Systemzeit Minuten"},
    "SYSTEMZEIT_STD": {"en": "System time hours", "de": "Systemzeit Stunden"},
    "SYSTEMZEIT_TAG": {"en": "System time day", "de": "Systemzeit Tag"},
    "SYSTEMZEIT_MONAT": {"en": "System time month", "de": "Systemzeit Monat"},
    "SYSTEMZEIT_JAHR": {"en": "System time year", "de": "Systemzeit Jahr"},
    "BETRIEBSST_TXT": {"en": "Operating state text", "de": "Betriebszustand Text"},
    # Phone settings (analog 85-87)
    "Handy_Vorwahl": {"en": "Mobile phone area code", "de": "Handy Vorwahl"},
    "Handy_Rufnummer": {"en": "Mobile phone number", "de": "Handy Rufnummer"},
    "TWW_Freigabe": {"en": "Hot water enable", "de": "Warmwasser Freigabe"},
    # Boiler flow/return (analog 88-89)
    "Kessel_Vorlauf": {"en": "Boiler flow temperature", "de": "Kessel Vorlauftemperatur"},
    "Kessel_Ruecklauf": {"en": "Boiler return temperature", "de": "Kessel Rücklauftemperatur"},
    # Heating circuits HK5-HK8 differentials (analog 90-93)
    "Diff_HK5": {"en": "Heating circuit 5 differential", "de": "Heizkreis 5 Differenz"},
    "Diff_HK6": {"en": "Heating circuit 6 differential", "de": "Heizkreis 6 Differenz"},
    "Diff_HK7": {"en": "Heating circuit 7 differential", "de": "Heizkreis 7 Differenz"},
    "Diff_HK8": {"en": "Heating circuit 8 differential", "de": "Heizkreis 8 Differenz"},
    # Heating circuits HK5-HK8 temperatures (analog 94-109)
    "HK5_VL": {"en": "Heating circuit 5 flow temperature", "de": "Heizkreis 5 Vorlauftemperatur"},
    "HK5_VLsoll": {"en": "Heating circuit 5 flow target", "de": "Heizkreis 5 Vorlauf Soll"},
    "HK5_RT": {"en": "Heating circuit 5 room temperature", "de": "Heizkreis 5 Raumtemperatur"},
    "HK5_RTsoll": {"en": "Heating circuit 5 room target", "de": "Heizkreis 5 Raum Soll"},
    "HK6_VL": {"en": "Heating circuit 6 flow temperature", "de": "Heizkreis 6 Vorlauftemperatur"},
    "HK6_VLsoll": {"en": "Heating circuit 6 flow target", "de": "Heizkreis 6 Vorlauf Soll"},
    "HK6_RT": {"en": "Heating circuit 6 room temperature", "de": "Heizkreis 6 Raumtemperatur"},
    "HK6_RTsoll": {"en": "Heating circuit 6 room target", "de": "Heizkreis 6 Raum Soll"},
    "HK7_VL": {"en": "Heating circuit 7 flow temperature", "de": "Heizkreis 7 Vorlauftemperatur"},
    "HK7_VLsoll": {"en": "Heating circuit 7 flow target", "de": "Heizkreis 7 Vorlauf Soll"},
    "HK7_RT": {"en": "Heating circuit 7 room temperature", "de": "Heizkreis 7 Raumtemperatur"},
    "HK7_RTsoll": {"en": "Heating circuit 7 room target", "de": "Heizkreis 7 Raum Soll"},
    "HK8_VL": {"en": "Heating circuit 8 flow temperature", "de": "Heizkreis 8 Vorlauftemperatur"},
    "HK8_VLsoll": {"en": "Heating circuit 8 flow target", "de": "Heizkreis 8 Vorlauf Soll"},
    "HK8_RT": {"en": "Heating circuit 8 room temperature", "de": "Heizkreis 8 Raumtemperatur"},
    "HK8_RTsoll": {"en": "Heating circuit 8 room target", "de": "Heizkreis 8 Raum Soll"},
    # System status (analog 110-111)
    "MODBUS_STOERUNG": {"en": "Modbus error", "de": "Modbus Störung"},
    "Status": {"en": "System status", "de": "Systemstatus"},
    # Digital outputs - Motors and pumps (digital 1000-1015)
    "M1_Kes_Ladepump": {"en": "Boiler charging pump", "de": "Kessel Ladepumpe"},
    "M2_Boilerpumpe": {"en": "Hot water pump", "de": "Boilerpumpe"},
    "M3_Zubringer": {"en": "Feeder", "de": "Zubringer"},
    "M4_Einschubmotor": {"en": "Insert motor", "de": "Einschubmotor"},
    "M5_Entaschung": {"en": "Ash removal", "de": "Entaschung"},
    "M6_E_Filter": {"en": "E-filter", "de": "E-Filter"},
    "M7_Saugzug": {"en": "Induced draft fan", "de": "Saugzuggebläse"},
    "M8_Zündung": {"en": "Ignition", "de": "Zündung"},
    "M9_HK1_Pumpe": {"en": "Heating circuit 1 pump", "de": "Heizkreis 1 Pumpe"},
    "M10_HK1_Mischer_Auf": {"en": "Heating circuit 1 mixer open", "de": "Heizkreis 1 Mischer Auf"},
    "M11_HK1_Mischer_Zu": {"en": "Heating circuit 1 mixer close", "de": "Heizkreis 1 Mischer Zu"},
    "M12_HK2_Pumpe": {"en": "Heating circuit 2 pump", "de": "Heizkreis 2 Pumpe"},
    "M13_HK2_Mischer_Auf": {"en": "Heating circuit 2 mixer open", "de": "Heizkreis 2 Mischer Auf"},
    "M14_HK2_Mischer_Zu": {"en": "Heating circuit 2 mixer close", "de": "Heizkreis 2 Mischer Zu"},
    "M15_Pufferpumpe": {"en": "Buffer pump", "de": "Pufferpumpe"},
    "M16_Solar": {"en": "Solar pump", "de": "Solarpumpe"},
    # System states (digital 1016-1027)
    "Stoerung": {"en": "Error", "de": "Störung"},
    "Handbetrieb": {"en": "Manual mode", "de": "Handbetrieb"},
    "Automatik": {"en": "Automatic mode", "de": "Automatik"},
    "Heizen": {"en": "Heating", "de": "Heizen"},
    "M17_HK3_Pumpe": {"en": "Heating circuit 3 pump", "de": "Heizkreis 3 Pumpe"},
    "M18_HK3_Mischer_Auf": {"en": "Heating circuit 3 mixer open", "de": "Heizkreis 3 Mischer Auf"},
    "M19_HK3_Mischer_Zu": {"en": "Heating circuit 3 mixer close", "de": "Heizkreis 3 Mischer Zu"},
    "M20_HK4_Pumpe": {"en": "Heating circuit 4 pump", "de": "Heizkreis 4 Pumpe"},
    "M21_HK4_Mischer_Auf": {"en": "Heating circuit 4 mixer open", "de": "Heizkreis 4 Mischer Auf"},
    "M22_HK4_Mischer_Zu": {"en": "Heating circuit 4 mixer close", "de": "Heizkreis 4 Mischer Zu"},
    "M23_Zirkulationspumpe": {"en": "Circulation pump", "de": "Zirkulationspumpe"},
    # HK1 modes (digital 1028-1031)
    "HK1_Modus_Auto": {"en": "Heating circuit 1 mode auto", "de": "Heizkreis 1 Modus Auto"},
    "HK1_Modus_Party": {"en": "Heating circuit 1 mode party", "de": "Heizkreis 1 Modus Party"},
    "HK1_Modus_Ferien": {"en": "Heating circuit 1 mode vacation", "de": "Heizkreis 1 Modus Ferien"},
    "HK1_Modus_Sparbetrieb": {"en": "Heating circuit 1 mode economy", "de": "Heizkreis 1 Modus Sparbetrieb"},
    # Digital inputs (digital 1032-1047)
    "E1_Aschelade_Endschalter": {"en": "Ash drawer limit switch", "de": "Aschelade Endschalter"},
    "E2_Türkontaktschalter": {"en": "Door contact switch", "de": "Türkontaktschalter"},
    "E3_Kesseltemp_Stoerung": {"en": "Boiler temperature error", "de": "Kesseltemperatur Störung"},
    "E4_Silo_Fuellstandsmelder": {"en": "Silo level indicator", "de": "Silo Füllstandsmelder"},
    "E5_Ext_Anforderung": {"en": "External request", "de": "Externe Anforderung"},
    "E6_Funk_Raumthermostat": {"en": "Wireless room thermostat", "de": "Funk Raumthermostat"},
    "E7_Stoermeldung_Kessel_gelb": {"en": "Boiler error yellow", "de": "Störmeldung Kessel gelb"},
    "E8_Stoermeldung_Kessel_rot": {"en": "Boiler error red", "de": "Störmeldung Kessel rot"},
    "E9_Ext_HK1_Anforderung": {"en": "External heating circuit 1 request", "de": "Externe HK1 Anforderung"},
    "E10_Ext_HK2_Anforderung": {"en": "External heating circuit 2 request", "de": "Externe HK2 Anforderung"},
    "E11_Saugturbine_Stoerung": {"en": "Induced draft fan error", "de": "Saugturbine Störung"},
    "E12_Fehlerstrom_Schutzschalter": {"en": "Residual current circuit breaker", "de": "Fehlerstrom Schutzschalter"},
    "E13_Pufferspeicher_Anforderung": {"en": "Buffer storage request", "de": "Pufferspeicher Anforderung"},
    "E14_Ext_HK3_Anforderung": {"en": "External heating circuit 3 request", "de": "Externe HK3 Anforderung"},
    "E15_Ext_HK4_Anforderung": {"en": "External heating circuit 4 request", "de": "Externe HK4 Anforderung"},
    "E16_Pelletbehaelter_fast_leer": {"en": "Pellet container almost empty", "de": "Pelletbehälter fast leer"},
    # HK2-HK4 modes (digital 1048-1063)
    "HK2_Modus_Auto": {"en": "Heating circuit 2 mode auto", "de": "Heizkreis 2 Modus Auto"},
    "HK2_Modus_Party": {"en": "Heating circuit 2 mode party", "de": "Heizkreis 2 Modus Party"},
    "HK2_Modus_Ferien": {"en": "Heating circuit 2 mode vacation", "de": "Heizkreis 2 Modus Ferien"},
    "HK2_Modus_Sparbetrieb": {"en": "Heating circuit 2 mode economy", "de": "Heizkreis 2 Modus Sparbetrieb"},
    "HK3_Modus_Auto": {"en": "Heating circuit 3 mode auto", "de": "Heizkreis 3 Modus Auto"},
    "HK3_Modus_Party": {"en": "Heating circuit 3 mode party", "de": "Heizkreis 3 Modus Party"},
    "HK3_Modus_Ferien": {"en": "Heating circuit 3 mode vacation", "de": "Heizkreis 3 Modus Ferien"},
    "HK3_Modus_Sparbetrieb": {"en": "Heating circuit 3 mode economy", "de": "Heizkreis 3 Modus Sparbetrieb"},
    "HK4_Modus_Auto": {"en": "Heating circuit 4 mode auto", "de": "Heizkreis 4 Modus Auto"},
    "HK4_Modus_Party": {"en": "Heating circuit 4 mode party", "de": "Heizkreis 4 Modus Party"},
    "HK4_Modus_Ferien": {"en": "Heating circuit 4 mode vacation", "de": "Heizkreis 4 Modus Ferien"},
    "HK4_Modus_Sparbetrieb": {"en": "Heating circuit 4 mode economy", "de": "Heizkreis 4 Modus Sparbetrieb"},
    "Stoerung_vorhanden": {"en": "Error present", "de": "Störung vorhanden"},
    "M24_Reserve_1": {"en": "Reserve output 1", "de": "Reserve Ausgang 1"},
    "M25_Reserve_2": {"en": "Reserve output 2", "de": "Reserve Ausgang 2"},
    "M26_Reserve_3": {"en": "Reserve output 3", "de": "Reserve Ausgang 3"},
    # HK1-HK4 states (digital 1064-1083)
    "HK1_Abgesenkt": {"en": "Heating circuit 1 lowered", "de": "Heizkreis 1 Abgesenkt"},
    "HK1_Normal": {"en": "Heating circuit 1 normal", "de": "Heizkreis 1 Normal"},
    "HK1_Party_Countdown": {"en": "Heating circuit 1 party countdown", "de": "Heizkreis 1 Party Countdown"},
    "HK1_Ferien_Programm": {"en": "Heating circuit 1 vacation program", "de": "Heizkreis 1 Ferienprogramm"},
    "HK1_Sommerzeit": {"en": "Heating circuit 1 summer time", "de": "Heizkreis 1 Sommerzeit"},
    "HK2_Abgesenkt": {"en": "Heating circuit 2 lowered", "de": "Heizkreis 2 Abgesenkt"},
    "HK2_Normal": {"en": "Heating circuit 2 normal", "de": "Heizkreis 2 Normal"},
    "HK2_Party_Countdown": {"en": "Heating circuit 2 party countdown", "de": "Heizkreis 2 Party Countdown"},
    "HK2_Ferien_Programm": {"en": "Heating circuit 2 vacation program", "de": "Heizkreis 2 Ferienprogramm"},
    "HK2_Sommerzeit": {"en": "Heating circuit 2 summer time", "de": "Heizkreis 2 Sommerzeit"},
    "HK3_Abgesenkt": {"en": "Heating circuit 3 lowered", "de": "Heizkreis 3 Abgesenkt"},
    "HK3_Normal": {"en": "Heating circuit 3 normal", "de": "Heizkreis 3 Normal"},
    "HK3_Party_Countdown": {"en": "Heating circuit 3 party countdown", "de": "Heizkreis 3 Party Countdown"},
    "HK3_Ferien_Programm": {"en": "Heating circuit 3 vacation program", "de": "Heizkreis 3 Ferienprogramm"},
    "HK3_Sommerzeit": {"en": "Heating circuit 3 summer time", "de": "Heizkreis 3 Sommerzeit"},
    "HK4_Abgesenkt": {"en": "Heating circuit 4 lowered", "de": "Heizkreis 4 Abgesenkt"},
    "HK4_Normal": {"en": "Heating circuit 4 normal", "de": "Heizkreis 4 Normal"},
    "HK4_Party_Countdown": {"en": "Heating circuit 4 party countdown", "de": "Heizkreis 4 Party Countdown"},
    "HK4_Ferien_Programm": {"en": "Heating circuit 4 vacation program", "de": "Heizkreis 4 Ferienprogramm"},
    "HK4_Sommerzeit": {"en": "Heating circuit 4 summer time", "de": "Heizkreis 4 Sommerzeit"},
    # HK5-HK8 motors (digital 1084-1095)
    "M27_HK5_Pumpe": {"en": "Heating circuit 5 pump", "de": "Heizkreis 5 Pumpe"},
    "M28_HK5_Mischer_Auf": {"en": "Heating circuit 5 mixer open", "de": "Heizkreis 5 Mischer Auf"},
    "M29_HK5_Mischer_Zu": {"en": "Heating circuit 5 mixer close", "de": "Heizkreis 5 Mischer Zu"},
    "M30_HK6_Pumpe": {"en": "Heating circuit 6 pump", "de": "Heizkreis 6 Pumpe"},
    "M31_HK6_Mischer_Auf": {"en": "Heating circuit 6 mixer open", "de": "Heizkreis 6 Mischer Auf"},
    "M32_HK6_Mischer_Zu": {"en": "Heating circuit 6 mixer close", "de": "Heizkreis 6 Mischer Zu"},
    "M33_HK7_Pumpe": {"en": "Heating circuit 7 pump", "de": "Heizkreis 7 Pumpe"},
    "M34_HK7_Mischer_Auf": {"en": "Heating circuit 7 mixer open", "de": "Heizkreis 7 Mischer Auf"},
    "M35_HK7_Mischer_Zu": {"en": "Heating circuit 7 mixer close", "de": "Heizkreis 7 Mischer Zu"},
    "M36_HK8_Pumpe": {"en": "Heating circuit 8 pump", "de": "Heizkreis 8 Pumpe"},
    "M37_HK8_Mischer_Auf": {"en": "Heating circuit 8 mixer open", "de": "Heizkreis 8 Mischer Auf"},
    "M38_HK8_Mischer_Zu": {"en": "Heating circuit 8 mixer close", "de": "Heizkreis 8 Mischer Zu"},
    # HK5-HK8 modes (digital 1096-1111)
    "HK5_Modus_Auto": {"en": "Heating circuit 5 mode auto", "de": "Heizkreis 5 Modus Auto"},
    "HK5_Modus_Party": {"en": "Heating circuit 5 mode party", "de": "Heizkreis 5 Modus Party"},
    "HK5_Modus_Ferien": {"en": "Heating circuit 5 mode vacation", "de": "Heizkreis 5 Modus Ferien"},
    "HK5_Modus_Sparbetrieb": {"en": "Heating circuit 5 mode economy", "de": "Heizkreis 5 Modus Sparbetrieb"},
    "HK6_Modus_Auto": {"en": "Heating circuit 6 mode auto", "de": "Heizkreis 6 Modus Auto"},
    "HK6_Modus_Party": {"en": "Heating circuit 6 mode party", "de": "Heizkreis 6 Modus Party"},
    "HK6_Modus_Ferien": {"en": "Heating circuit 6 mode vacation", "de": "Heizkreis 6 Modus Ferien"},
    "HK6_Modus_Sparbetrieb": {"en": "Heating circuit 6 mode economy", "de": "Heizkreis 6 Modus Sparbetrieb"},
    "HK7_Modus_Auto": {"en": "Heating circuit 7 mode auto", "de": "Heizkreis 7 Modus Auto"},
    "HK7_Modus_Party": {"en": "Heating circuit 7 mode party", "de": "Heizkreis 7 Modus Party"},
    "HK7_Modus_Ferien": {"en": "Heating circuit 7 mode vacation", "de": "Heizkreis 7 Modus Ferien"},
    "HK7_Modus_Sparbetrieb": {"en": "Heating circuit 7 mode economy", "de": "Heizkreis 7 Modus Sparbetrieb"},
    "HK8_Modus_Auto": {"en": "Heating circuit 8 mode auto", "de": "Heizkreis 8 Modus Auto"},
    "HK8_Modus_Party": {"en": "Heating circuit 8 mode party", "de": "Heizkreis 8 Modus Party"},
    "HK8_Modus_Ferien": {"en": "Heating circuit 8 mode vacation", "de": "Heizkreis 8 Modus Ferien"},
    "HK8_Modus_Sparbetrieb": {"en": "Heating circuit 8 mode economy", "de": "Heizkreis 8 Modus Sparbetrieb"},
}
