#!/usr/bin/env python3
"""DAQ File Parser for Hargassner Boiler Log Files.

This tool extracts firmware templates and system information from DAQ files
generated by Hargassner boilers, making it easy for developers to add support
for new firmware versions.

Usage:
    python daq_parser.py <daq_file> [--output <format>]

Examples:
    python daq_parser.py DAQ00000.DAQ
    python daq_parser.py DAQ00000.DAQ --output json
    python daq_parser.py DAQ00000.DAQ --output python
"""

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class SystemInfo:
    """System information extracted from DAQ file."""

    manufacturer: str = ""
    model: str = ""
    software_version: str = ""
    hardware_version: str = ""
    serial_number: str = ""
    serial_io: str = ""
    serial_bce: str = ""
    update_date: str = ""
    update_info: str = ""
    control_hours: str = ""
    heating_hours: str = ""
    ignition_hours: str = ""
    draft_hours: str = ""
    delivery_hours: str = ""
    discharge_hours: str = ""
    ash_screw_hours: str = ""
    dongle_class: str = ""
    dongle_code: str = ""
    firmware_info: List[str] = None

    def __post_init__(self):
        if self.firmware_info is None:
            self.firmware_info = []


@dataclass
class ParameterInfo:
    """Parameter information from DAQPRJ template."""

    id: int
    name: str
    unit: Optional[str] = None
    dop: Optional[str] = None
    is_digital: bool = False
    bit: Optional[int] = None


@dataclass
class DAQData:
    """Complete DAQ file data."""

    system_info: SystemInfo
    daqprj_template: str
    analog_parameters: List[ParameterInfo]
    digital_parameters: List[ParameterInfo]
    sample_messages: List[str]
    raw_header: str


class DAQParser:
    """Parser for Hargassner DAQ log files."""

    def __init__(self, file_path: str):
        """Initialize parser with DAQ file path.

        Args:
            file_path: Path to DAQ file
        """
        self.file_path = Path(file_path)
        self.raw_content = ""
        self.lines = []

    def parse(self) -> DAQData:
        """Parse DAQ file and extract all information.

        Returns:
            DAQData object with all extracted information
        """
        # Read file with multiple encoding attempts
        self.raw_content = self._read_file()
        self.lines = self.raw_content.split("\n")

        # Extract components
        header = self._extract_header()
        daqprj = self._extract_daqprj()
        system_info = self._extract_system_info()
        analog_params, digital_params = self._parse_daqprj(daqprj)
        sample_messages = self._extract_sample_messages()

        return DAQData(
            system_info=system_info,
            daqprj_template=daqprj,
            analog_parameters=analog_params,
            digital_parameters=digital_params,
            sample_messages=sample_messages,
            raw_header=header,
        )

    def _read_file(self) -> str:
        """Read file with encoding detection.

        Returns:
            File content as string
        """
        for encoding in ["utf-8", "latin-1", "cp1252", "iso-8859-1"]:
            try:
                with open(self.file_path, "r", encoding=encoding, errors="replace") as f:
                    content = f.read()
                    # Replace common problematic characters
                    content = content.replace("�", "°")
                    return content
            except Exception:
                continue

        # Fallback: binary read with replace
        with open(self.file_path, "rb") as f:
            return f.read().decode("utf-8", errors="replace")

    def _extract_header(self) -> str:
        """Extract DAQ header line.

        Returns:
            Header string
        """
        if self.lines:
            return self.lines[0].strip()
        return ""

    def _extract_daqprj(self) -> str:
        """Extract DAQPRJ XML template.

        Returns:
            DAQPRJ XML string
        """
        for line in self.lines:
            if line.strip().startswith("<DAQPRJ>"):
                return line.strip()
        return ""

    def _extract_system_info(self) -> SystemInfo:
        """Extract system information from DAQ file.

        Returns:
            SystemInfo object
        """
        info = SystemInfo()

        # Patterns for information extraction
        patterns = {
            "manufacturer": r"KD=(.+)",
            "model": r"KT=(.+)",
            "software_version": r"SW=(.+)",
            "hardware_version": r"HW=(.+)",
            "serial_number": r"KN=(\d+)",
            "serial_io": r"SNIO=(\d+)",
            "serial_bce": r"SNBCE=(\d+)",
            "update_date": r"UPDATEDATE=(.+)",
            "update_info": r"UPDATE=(.+)",
            "control_hours": r"STEUERUNG=(.+)",
            "heating_hours": r"HEIZUNG=(.+)",
            "ignition_hours": r"ZUENDUNG=(.+)",
            "draft_hours": r"SAUGZUG=(.+)",
            "delivery_hours": r"EINSCHUB=(.+)",
            "discharge_hours": r"AUSTRAGUNG=(.+)",
            "ash_screw_hours": r"ASCHESCHNECKE=(.+)",
        }

        for line in self.lines[:100]:  # Check first 100 lines
            for field, pattern in patterns.items():
                match = re.search(pattern, line)
                if match:
                    setattr(info, field, match.group(1).strip())

            # Extract dongle info
            if "zLeistungsklasse:" in line:
                info.dongle_class = line.split(":")[-1].strip()
            if "zSystemcode:" in line:
                info.dongle_code = line.split(":")[-1].strip()

            # Extract firmware info
            if "IO38/IO49" in line or "HW=V" in line:
                if line.strip() not in info.firmware_info:
                    info.firmware_info.append(line.strip())

        return info

    def _parse_daqprj(
        self, daqprj_xml: str
    ) -> Tuple[List[ParameterInfo], List[ParameterInfo]]:
        """Parse DAQPRJ XML template.

        Args:
            daqprj_xml: DAQPRJ XML string

        Returns:
            Tuple of (analog_parameters, digital_parameters)
        """
        if not daqprj_xml:
            return [], []

        try:
            root = ET.fromstring(daqprj_xml)
        except ET.ParseError as e:
            print(f"Warning: Failed to parse DAQPRJ XML: {e}", file=sys.stderr)
            return [], []

        analog_params = []
        digital_params = []

        # Parse analog channels
        for channel in root.findall(".//ANALOG/CHANNEL"):
            param = ParameterInfo(
                id=int(channel.get("id", 0)),
                name=channel.get("name", "Unknown"),
                unit=channel.get("unit"),
                dop=channel.get("dop"),
                is_digital=False,
            )
            analog_params.append(param)

        # Parse digital channels
        for channel in root.findall(".//DIGITAL/CHANNEL"):
            param = ParameterInfo(
                id=int(channel.get("id", 0)),
                name=channel.get("name", "Unknown"),
                bit=int(channel.get("bit", 0)),
                is_digital=True,
            )
            digital_params.append(param)

        return analog_params, digital_params

    def _extract_sample_messages(self, max_samples: int = 10) -> List[str]:
        """Extract sample telnet messages (pm lines).

        Args:
            max_samples: Maximum number of samples to extract

        Returns:
            List of sample message strings
        """
        messages = []

        for line in self.lines:
            if line.strip().startswith("pm "):
                # Clean message
                clean_msg = line.strip()
                # Remove timestamps if present
                clean_msg = re.sub(r"^\d{4}-\d{2}-\d{2}_\d{2}:\d{2}:\d{2}\s+", "", clean_msg)
                messages.append(clean_msg)

                if len(messages) >= max_samples:
                    break

        return messages


class OutputFormatter:
    """Format DAQ data for different output types."""

    @staticmethod
    def format_json(data: DAQData) -> str:
        """Format as JSON.

        Args:
            data: DAQData object

        Returns:
            JSON string
        """
        output = {
            "system_info": asdict(data.system_info),
            "daqprj_template": data.daqprj_template,
            "analog_parameters": [asdict(p) for p in data.analog_parameters],
            "digital_parameters": [asdict(p) for p in data.digital_parameters],
            "sample_messages": data.sample_messages,
            "statistics": {
                "total_analog": len(data.analog_parameters),
                "total_digital": len(data.digital_parameters),
                "expected_message_length": len(data.analog_parameters)
                + (
                    max([p.id for p in data.digital_parameters], default=0) + 1
                    if data.digital_parameters
                    else 0
                ),
            },
        }

        return json.dumps(output, indent=2, ensure_ascii=False)

    @staticmethod
    def format_python(data: DAQData) -> str:
        """Format as Python code for firmware_templates.py.

        Args:
            data: DAQData object

        Returns:
            Python code string
        """
        firmware_id = data.system_info.software_version.replace(".", "_").replace("-", "_")
        if not firmware_id:
            firmware_id = "UNKNOWN_VERSION"

        output = f'''"""
Firmware Template: {firmware_id}
Generated from DAQ file

System Information:
- Manufacturer: {data.system_info.manufacturer}
- Model: {data.system_info.model}
- Software: {data.system_info.software_version}
- Hardware: {data.system_info.hardware_version}
- Serial: {data.system_info.serial_number}

Statistics:
- Analog Parameters: {len(data.analog_parameters)}
- Digital Parameters: {len(data.digital_parameters)}
- Expected Message Length: {len(data.analog_parameters) + (max([p.id for p in data.digital_parameters], default=0) + 1 if data.digital_parameters else 0)}
"""

# Add to FIRMWARE_TEMPLATES in firmware_templates.py
FIRMWARE_TEMPLATES["{firmware_id}"] = """{data.daqprj_template}"""

# Add to FIRMWARE_VERSIONS in const.py
FIRMWARE_VERSIONS.append("{firmware_id}")

# Sample telnet messages for testing:
# {data.sample_messages[0] if data.sample_messages else 'No samples found'}
'''
        return output

    @staticmethod
    def format_text(data: DAQData) -> str:
        """Format as human-readable text.

        Args:
            data: DAQData object

        Returns:
            Formatted text string
        """
        lines = []
        lines.append("=" * 70)
        lines.append("DAQ FILE ANALYSIS")
        lines.append("=" * 70)

        # System Info
        lines.append("\nSYSTEM INFORMATION:")
        lines.append(f"  Manufacturer:      {data.system_info.manufacturer}")
        lines.append(f"  Model:             {data.system_info.model}")
        lines.append(f"  Software Version:  {data.system_info.software_version}")
        lines.append(f"  Hardware Version:  {data.system_info.hardware_version}")
        lines.append(f"  Serial Number:     {data.system_info.serial_number}")
        lines.append(f"  Serial IO:         {data.system_info.serial_io}")
        lines.append(f"  Serial BCE:        {data.system_info.serial_bce}")

        # Operating Hours
        lines.append("\nOPERATING HOURS:")
        lines.append(f"  Control:           {data.system_info.control_hours}")
        lines.append(f"  Heating:           {data.system_info.heating_hours}")
        lines.append(f"  Ignition:          {data.system_info.ignition_hours}")
        lines.append(f"  Draft:             {data.system_info.draft_hours}")

        # Dongle Info
        if data.system_info.dongle_class:
            lines.append("\nDONGLE INFORMATION:")
            lines.append(f"  Class:             {data.system_info.dongle_class}")
            lines.append(f"  System Code:       {data.system_info.dongle_code}")

        # Firmware
        if data.system_info.firmware_info:
            lines.append("\nFIRMWARE MODULES:")
            for fw in data.system_info.firmware_info:
                lines.append(f"  - {fw}")

        # Parameters
        lines.append("\nPARAMETER STATISTICS:")
        lines.append(f"  Analog Parameters:  {len(data.analog_parameters)}")
        lines.append(f"  Digital Parameters: {len(data.digital_parameters)}")

        digital_count = (
            max([p.id for p in data.digital_parameters], default=0) + 1
            if data.digital_parameters
            else 0
        )
        lines.append(
            f"  Expected Msg Length: {len(data.analog_parameters) + digital_count}"
        )

        # Sample Analog Parameters
        lines.append("\nSAMPLE ANALOG PARAMETERS (first 10):")
        for param in data.analog_parameters[:10]:
            unit_str = f" [{param.unit}]" if param.unit else ""
            lines.append(f"  [{param.id:3d}] {param.name:30s}{unit_str}")
        if len(data.analog_parameters) > 10:
            lines.append(f"  ... and {len(data.analog_parameters) - 10} more")

        # Sample Digital Parameters
        if data.digital_parameters:
            lines.append("\nSAMPLE DIGITAL PARAMETERS (first 10):")
            for param in data.digital_parameters[:10]:
                lines.append(f"  [{param.id}:{param.bit}] {param.name}")
            if len(data.digital_parameters) > 10:
                lines.append(f"  ... and {len(data.digital_parameters) - 10} more")

        # Sample Messages
        if data.sample_messages:
            lines.append("\nSAMPLE TELNET MESSAGES:")
            for i, msg in enumerate(data.sample_messages[:3], 1):
                # Truncate long messages
                if len(msg) > 100:
                    msg = msg[:100] + "..."
                lines.append(f"  {i}. {msg}")

        lines.append("\n" + "=" * 70)

        return "\n".join(lines)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Parse Hargassner DAQ files and extract firmware templates",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python daq_parser.py DAQ00000.DAQ
  python daq_parser.py DAQ00000.DAQ --output json
  python daq_parser.py DAQ00000.DAQ --output python > new_firmware.txt
        """,
    )

    parser.add_argument("file", help="DAQ file to parse")
    parser.add_argument(
        "--output",
        "-o",
        choices=["text", "json", "python"],
        default="text",
        help="Output format (default: text)",
    )

    args = parser.parse_args()

    # Check file exists
    if not Path(args.file).exists():
        print(f"Error: File not found: {args.file}", file=sys.stderr)
        sys.exit(1)

    # Parse file
    try:
        daq_parser = DAQParser(args.file)
        data = daq_parser.parse()
    except Exception as e:
        print(f"Error parsing DAQ file: {e}", file=sys.stderr)
        sys.exit(1)

    # Format output
    formatter = OutputFormatter()

    if args.output == "json":
        output = formatter.format_json(data)
    elif args.output == "python":
        output = formatter.format_python(data)
    else:  # text
        output = formatter.format_text(data)

    # Safe output handling for Windows console
    try:
        print(output)
    except UnicodeEncodeError:
        # Fallback for Windows console with limited encoding
        print(output.encode(sys.stdout.encoding, errors='replace').decode(sys.stdout.encoding))


if __name__ == "__main__":
    main()
